app_name: "fore"

log_file: 'log.txt'
log_format: '%(asctime)s P%(process)-5d (%(levelname)8s) %(module)16s%(lineno)5d: %(uid)9s %(message)s'
log_config_file_changes: False

lag_limit: 88200        #   samples - how much we can lag by before dropping frames.
restart_timeout: 3      #   seconds between polls to restart.txt
http_port: 8192
socket_port: 8193
audition_http_port: 8198
audition_socket_port: 8199
frontend_buffer: 20    #   seconds of audio to buffer in frontend
past_played_buffer: 600 #   seconds of audio to store track metadata for in the past
monitor_update_time: 0.5
template_dir: templates/
drift_limit: 0.1        #   seconds of audio after which drift should be corrected

max_track_length: 400
min_track_length: 90

#   Default values when nothing exists
no_bpm_diff: 20
